FROM openjdk:11

ENV HBASE_VERSION=2.2.7

RUN cd /opt && \
    wget -q https://archive.apache.org/dist/hbase/${HBASE_VERSION}/hbase-${HBASE_VERSION}-bin.tar.gz && \
    tar xzf hbase-${HBASE_VERSION}-bin.tar.gz

WORKDIR /opt/hbase-${HBASE_VERSION}

COPY hbase-site.zk.xml conf/hbase-site.xml

CMD ./bin/start-hbase.sh && tail -F logs/hbase*.log
